[package]
name = "pcp-client"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

[dependencies]
pcp-proto = { version = "0.1", path = "../pcp-proto" }

anyhow = "1"
thiserror = "1"
tokio = { version = "1", features = ["net", "time"] }
tracing = "0.1"
